# Generated by Django 3.0.8 on 2020-09-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
